services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/chat
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CLIENT_URL=http://localhost:8090
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo
    ports:
      - "27017:27017"