services:
    backend:
        build: ./backend
        ports:
        - "3000:3000"
        environment:
        - MONGO_URI=mongodb://mongo:27017/chat
    frontend:
        build: ./frontend
        ports:
        - "8080:8080"
    mongo:
        image: mongo
        ports:
        - "27017:27017"
